export enum ActionType {
  SET_WEIGHINGS = 'SET_WEIGHINGS',
  ADD_WEIGHING = 'ADD_WEIGHING',
  EDIT_WEIGHING = 'EDIT_WEIGHING',
  DELETE_WEIGHING = 'DELETE_WEIGHING',
  SHOW_SUCCESS_NOTIFICATION = 'SHOW_SUCCESS_NOTIFICATION',
  SHOW_ERROR_NOTIFICATION = 'SHOW_ERROR_NOTIFICATION',
  HIDE_NOTIFICATION = 'HIDE_NOTIFICATION',
}
